//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNT.Shared.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GNT.Shared.Translate.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Bundle.
        /// </summary>
        public static string ProductType_Bundle {
            get {
                return ResourceManager.GetString("ProductType_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Session.
        /// </summary>
        public static string ProductType_Consultation {
            get {
                return ResourceManager.GetString("ProductType_Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Product.
        /// </summary>
        public static string ProductType_DigitalProduct {
            get {
                return ResourceManager.GetString("ProductType_DigitalProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Card.
        /// </summary>
        public static string ProductType_GiftCard {
            get {
                return ResourceManager.GetString("ProductType_GiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software License.
        /// </summary>
        public static string ProductType_License {
            get {
                return ResourceManager.GetString("ProductType_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Access.
        /// </summary>
        public static string ProductType_Membership {
            get {
                return ResourceManager.GetString("ProductType_Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ProductType_Other {
            get {
                return ResourceManager.GetString("ProductType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Good.
        /// </summary>
        public static string ProductType_PhysicalGood {
            get {
                return ResourceManager.GetString("ProductType_PhysicalGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string ProductType_Service {
            get {
                return ResourceManager.GetString("ProductType_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Plan.
        /// </summary>
        public static string ProductType_Subscription {
            get {
                return ResourceManager.GetString("ProductType_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Coverage.
        /// </summary>
        public static string ProductType_Warranty {
            get {
                return ResourceManager.GetString("ProductType_Warranty", resourceCulture);
            }
        }
    }
}
